CREATE TABLE tb_ransaction_pin(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    pin VARCHAR(50) NOT NULL,
    attempt INT NOT NULL,
    blocked Bool NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)