CREATE TABLE tb_transactions(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    from_wallet BIGINT NOT NULL,
    to_wallet BIGINT NOT NULL,
    transaction_value DECIMAL(10, 2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)